name: Golangci-lint

on: [push]

jobs:
  golangci-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
      
      - name: Install golangci-lint
        run: curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.54.2
      
      - name: Run golangci-lint
        run: find . -name "go.mod" -execdir $(go env GOPATH)/bin/golangci-lint run --enable=gofmt --tests=false --exclude-use-default --timeout=5m0s --out-format json > golangci-lint-results.json \;

      - name: Check golangci-lint JSON report for errors
        run: if jq -e '.Issues[]' golangci-lint-results.json > /dev/null; then exit 1; else echo "No issues found"; fi

      - name: Upload golangci-lint JSON report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: golangci-lint-json-report
          path: ./golangci-lint-results.json
