name: Golangci-lint

on: [push]

jobs:
  golangci-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Build binary
        shell: bash
        run: go build ./...
          - name: golangci-lint
             uses: golangci/golangci-lint-action@aaa42aa0628b4ae2578232a66b541047968fac86 # v6.1.0
             with:
              version: v1.60.1
              # We already cache these directories in setup-go
              skip-pkg-cache: true
              skip-build-cache: true
              # only-new-issues is only applicable to PRs, otherwise it is always set to false
              only-new-issues: false # disabled for PRs due to unreliability
              args: --out-format colored-line-number,checkstyle:golangci-lint-report.xml
          - name: Print lint report artifact
            if: failure()
            shell: bash
            run: cat ${{ inputs.go-directory }}/golangci-lint-report.xml