name: Golangci-lint

on: [push]

jobs:
  golangci-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
      
      - name: Install golangci-lint
        run: curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.54.2
      
      - name: Run golangci-lint
        run: docker run --rm -v ${{ github.workspace }}:/app -w /app golangci/golangci-lint:v1.54.2 golangci-lint run --max-issues-per-linter 0 --max-same-issues 0 --out-format json > golangci-lint-results.json || true

      - name: Check golangci-lint JSON report for errors
        run: | 
          if jq -e '.Issues | length > 0' golangci-lint-results.json; then
              echo "Lint issues found:" 
              jq '.Issues[] | "\(.FromLinter): \(.Pos.Filename):\(.Pos.Line) \(.Text)"' golangci-lint-results.json
              exit 1
          else 
              echo "No issues found"
          fi

      - name: Upload golangci-lint JSON report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: golangci-lint-json-report
          path: ./golangci-lint-results.json
