name: OPS Build and Test

on: [push]

jobs:
  relay-ops:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version-file: 'go.mod'

      - name: Build ops
        run: cd ops && go build -v

      - name: Unit test ops
        run: cd ops && go test ./... -coverpkg=./... -coverprofile=ops_coverage.out
      
      - name: Upload Go ops test results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: go-test-results
          path: ./ops/ops_coverage.out