name: PKG Build and Test

on: [push ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version-file: 'go.mod'

      - name: Build
        run: go build -v ./...

      - name: Unit Tests
        run: go test -race ./... -coverpkg=./... -coverprofile=pkg_coverage.out
      
      - name: Fuzz Tests
        # The amount of --seconds here is subject to change based on how long the CI job takes in the future
        # as we add more fuzz tests, we should take into consideration increasing this timelapse, so we can have enough coverage.
        # We are timing out after ~10mins in case the tests hang. (Current CI duration is ~7m, modify if needed)
        run: cd fuzz && timeout 10m ./fuzz_all_native.py --ci --seconds 360
      
      - name: Upload Go test results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: go-test-results
          path: ./pkg_coverage.out
