name: Unit Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - "*"

jobs:
  relay-ops:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v1
        with:
          go-version: 1.18
      - name: Build
        run: cd ops && go build -v
      - name: Test
        run: cd ops && go test -v ./...
