name: Unit Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - "*"

jobs:
  relay-core:
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: postgres://postgres@localhost:5432/postgres?sslmode=disable
    services:
      postgres:
        image: postgres
        ports:
          - 5432:5432
        env:
          POSTGRES_HOST_AUTH_METHOD: trust
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v1
        with:
          go-version: 1.17
      - name: Build
        run: go build -v ./core/...
      - name: Test
        run: go test ./core/... -v
  relay-ops:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v1
        with:
          go-version: 1.17
      - name: Build
        run: cd ops && go build -v
      - name: Test
        run: cd ops && go test -v ./...
